Web Site/FSP.Web.4.5/Areas/AdminArea/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FSP.Domain.Model;
using FSP.Web.Areas.AdminArea.ViewModels;
using FSP.Web.Filters;

namespace FSP.Web.Areas.AdminArea.Controllers
{
    [CustomAuthorization(Roles = "Admin")]
    public class ContractController : Controller
    {
        private readonly FSPDataContext _db = new FSPDataContext();

        public ActionResult Create()
        {
            var model = new ContractCreateViewModel();
            var contract = new Contract
            {
                EndDate = DateTime.Today,
                StartDate = DateTime.Today
            };
            model.Contract = contract;
            model.SelectedBeats = new List<Guid>();

            ViewBag.Contractors = _db.Contractors.OrderBy(p => p.ContractCompanyName).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ContractCreateViewModel contractCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                //if Contract does not exist yet       
                var contractId = Guid.NewGuid();
                contractCreateViewModel.Contract.ContractID = contractId;
                contractCreateViewModel.Contract.BeatID = _db.vBeats.FirstOrDefault().BeatID; //obsolete
                _db.Contracts.InsertOnSubmit(contractCreateViewModel.Contract);
                _db.SubmitChanges();

                //add beats
                foreach (var beat in contractCreateViewModel.SelectedBeats)
                {
                    var contractsBeat = new ContractsBeat
                    {
                        BeatID = beat,
                        ContractID = contractId
                    };
                    _db.ContractsBeats.InsertOnSubmit(contractsBeat);
                }

                _db.SubmitChanges();

                return RedirectToAction("Index");
            }

            ViewBag.Contractors = _db.Contractors.OrderBy(p => p.ContractCompanyName).ToList();

            return View(contractCreateViewModel);
        }

        public ActionResult Delete(Guid id)
        {
            var contract = _db.Contracts.Single(r => r.ContractID == id);
            if (contract == null) return HttpNotFound();
            return View(contract);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var contract = _db.Contracts.Single(r => r.ContractID == id);
            _db.Contracts.DeleteOnSubmit(contract);
            _db.SubmitChanges();

            var existingBeats = _db.ContractsBeats.Where(p => p.ContractID == id);

            foreach (var existingBeat in existingBeats) _db.ContractsBeats.DeleteOnSubmit(existingBeat);

            _db.SubmitChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            var contract = _db.Contracts.Single(r => r.ContractID == id);

            if (contract == null) return HttpNotFound();

            var model = new ContractCreateViewModel
            {
                Contract = contract,
                SelectedBeats = new List<Guid>()
            };

            ViewBag.Contractors = _db.Contractors.OrderBy(p => p.ContractCompanyName).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ContractCreateViewModel contractCreateViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Contracts.Attach(contractCreateViewModel.Contract);
                    _db.Refresh(RefreshMode.KeepCurrentValues, contractCreateViewModel.Contract);
                    _db.SubmitChanges();

                    //remove existing ones
                    var existingBeats =
                        _db.ContractsBeats.Where(p => p.ContractID == contractCreateViewModel.Contract.ContractID);

                    foreach (var existingBeat in existingBeats) _db.ContractsBeats.DeleteOnSubmit(existingBeat);

                    _db.SubmitChanges();

                    //re-add beats
                    foreach (var beat in contractCreateViewModel.SelectedBeats)
                    {
                        var contractsBeat = new ContractsBeat();
                        contractsBeat.BeatID = beat;
                        contractsBeat.ContractID = contractCreateViewModel.Contract.ContractID;
                        _db.ContractsBeats.InsertOnSubmit(contractsBeat);
                    }

                    _db.SubmitChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }

            ViewBag.Contractors = _db.Contractors.OrderBy(p => p.ContractCompanyName).ToList();
            return View(contractCreateViewModel);
        }

        public ActionResult Index()
        {
            var dbContracts = _db.Contracts.OrderBy(p => p.Contractor.ContractCompanyName).ToList();
            var dbBeats = _db.Beats_News.Where(p => p.Active).OrderBy(p => p.BeatNumber).ToList();
            var dbContractsBeats = _db.ContractsBeats.ToList();

            var model = new ContractIndexViewModel();
            model.Contracts = new List<ContractIndex>();

            foreach (var dbContract in dbContracts)
            {
                var selectedBeats = (from q in dbContractsBeats
                                     join b in dbBeats on q.BeatID equals b.BeatID
                                     where q.ContractID == dbContract.ContractID
                                     orderby b.BeatNumber
                                     select b.BeatNumber).ToList();

                model.Contracts.Add(new ContractIndex
                {
                    Contract = dbContract,
                    SelectedBeats = selectedBeats.OrderBy(p => p).ToList()
                });
            }

            model.Contracts = model.Contracts.OrderBy(p => p.Contract.Contractor.ContractCompanyName)
                .ThenBy(p => p.SelectedBeats.FirstOrDefault()).ToList();

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web Site/FSP.Web.4.5/Areas/AdminArea/Views/Contract/Create.cshtml
@model FSP.Web.Areas.AdminArea.ViewModels.ContractCreateViewModel
@{
    ViewBag.Title = "Create";
    
}
<div>
    @Html.ActionLink("Back to Contracts", "Index")
</div>

<h2>New Contract</h2>


@using (Html.BeginForm("Create", "Contract", FormMethod.Post, new { id = "contractForm" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.AgreementNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.AgreementNumber)
            @Html.ValidationMessageFor(model => model.Contract.AgreementNumber)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.StartDate)
            @Html.ValidationMessageFor(model => model.Contract.StartDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.EndDate)
            @Html.ValidationMessageFor(model => model.Contract.EndDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.MaxObligation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.MaxObligation)
            @Html.ValidationMessageFor(model => model.Contract.MaxObligation)
        </div>

        <div class="editor-label">
            Available Beats
        </div>
        <div class="editor-field">
            <select data-bind="options: beats, optionsText: 'text', optionsValue: 'id', value: selectedBeatId"></select>
            <input class="btn btn-success" type="button" value="add" data-bind="click: addBeat" />
        </div>

        Selected Beats
        <hr />
        <div data-bind="visible: selectedBeats().length > 0">
            <div data-bind="foreach: selectedBeats">
                <span data-bind="text: text"></span>
                <input id="SelectedBeats" name="SelectedBeats" type="hidden" data-bind="value: id" />
                <input class="btn btn-warning" type="button" value="X" data-bind="click: $root.removeSelectedBeat" />
                <br />
            </div>
        </div>
        <hr />

        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.ContractorID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.Contract.ContractorID, new SelectList(ViewBag.Contractors, "ContractorID", "ContractCompanyName"), "--Select Contractor--", new { @class = "span8" })
            @Html.ValidationMessageFor(model => model.Contract.ContractorID)
        </div>


        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Create</button>
        </div>
    </fieldset>
}


@section scripts
{
    <script src="~/Scripts/knockout-2.2.1.js"></script>
    <script src="~/MyScripts/fsp.contract.create.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>

}

Web Site/FSP.Web.4.5/Areas/AdminArea/Views/Contract/Delete.cshtml
@model FSP.Domain.Model.Contract

@{
    ViewBag.Title = "Delete " + @Model.AgreementNumber;
    
}

<h2>Delete "@Model.AgreementNumber"</h2>

<h3>Are you sure you want to delete this contract?</h3>

@using (Html.BeginForm())
{
    <p>
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">
                Delete</button>
        </div>
    </p>
}

Web Site/FSP.Web.4.5/Areas/AdminArea/Views/Contract/Edit.cshtml
@model FSP.Web.Areas.AdminArea.ViewModels.ContractCreateViewModel
@{
    ViewBag.Title = "Edit " + @Model.Contract.AgreementNumber;
    
}
<div>
    @Html.ActionLink("Back to Contracts", "Index")
</div>

<h2>Edit "@Model.Contract.AgreementNumber"</h2>




@using (Html.BeginForm("Edit", "Contract", FormMethod.Post, new { id = "contractForm" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        @Html.HiddenFor(model => model.Contract.ContractID)
        @Html.HiddenFor(model => model.Contract.BeatID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.AgreementNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.AgreementNumber)
            @Html.ValidationMessageFor(model => model.Contract.AgreementNumber)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.StartDate)
            @Html.ValidationMessageFor(model => model.Contract.StartDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.EndDate)
            @Html.ValidationMessageFor(model => model.Contract.EndDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.MaxObligation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contract.MaxObligation)
            @Html.ValidationMessageFor(model => model.Contract.MaxObligation)
        </div>

        <div class="editor-label">
            Available Beats
        </div>
        <div class="editor-field">
            <select data-bind="options: beats, optionsText: 'text', optionsValue: 'id', value: selectedBeatId"></select>
            <input class="btn btn-success" type="button" value="add" data-bind="click: addBeat" />
        </div>

        Selected Beats
        <hr />
        <div data-bind="visible: selectedBeats().length > 0">
            <div data-bind="foreach: selectedBeats">
                <span data-bind="text: text"></span>
                <input id="SelectedBeats" name="SelectedBeats" type="hidden" data-bind="value: id" />
                <input class="btn btn-warning" type="button" value="X" data-bind="click: $root.removeSelectedBeat" title="remove" />
                <br />
                <br />
            </div>
        </div>
        <hr />


        <div class="editor-label">
            @Html.LabelFor(model => model.Contract.ContractorID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.Contract.ContractorID, new SelectList(ViewBag.Contractors, "ContractorID", "ContractCompanyName"), "--Select Contractor--", new { @class = "span8" })
            @Html.ValidationMessageFor(model => model.Contract.ContractorID)
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Update</button>
        </div>
    </fieldset>
}
@section scripts{
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/MyScripts/fsp.contract.create.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
}

Web Site/FSP.Web.4.5/Areas/AdminArea/Views/Contract/Index.cshtml
@model FSP.Web.Areas.AdminArea.ViewModels.ContractIndexViewModel
@{
    ViewBag.Title = "Contracts";    
}


<p>
    @Html.ActionLink("Add Contract", "Create")
</p>
<h2>Contracts</h2>
<table class="table table-condensed table-striped table-bordered table-hover sortable">
    <thead>
        <tr>
            <th>Agreement Number
            </th>
            <th>Start Date
            </th>
            <th>End Date
            </th>
            <th>Max Obligation
            </th>
            <th>Beats
            </th>
            <th>Contractor
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Contracts)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Contract.AgreementNumber, "Edit", new { id = item.Contract.ContractID })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contract.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contract.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contract.MaxObligation)
                </td>
                <td>
                    @foreach (var beat in item.SelectedBeats)
                    {
                        <ul style="list-style: none">
                            <li>@beat</li>
                        </ul>
                    }
                </td>
                <td>
                    @Html.ActionLink(item.Contract.Contractor.ContractCompanyName, "Edit", "Contractor", null, null, null, new { id = item.Contract.ContractorID }, null)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Contract.ContractID })
                </td>
            </tr>                                
        }
    </tbody>
</table>